//
// Created by lijie on 9/9/18.
//

#ifndef ARGUS_DISTRIBUTION_DISPLAY_HELPER_H
#define ARGUS_DISTRIBUTION_DISPLAY_HELPER_H

#ifdef WIN32
#include <windows.h>
#endif

#include <GL/glew.h>
#include <GLFW/glfw3.h>

#ifndef WIN32
#	define ARGUS_DISPLAY_EXPORT_DYNAMIC_LIBRARY
#   define ARGUS_SIMULATION_IMPORT_DYNAMIC_LIBRARY
#else
#	define ARGUS_DISPLAY_EXPORT_DYNAMIC_LIBRARY __declspec( dllexport )
#   define ARGUS_DISPLAY_IMPORT_DYNAMIC_LIBRARY __declspec( dllimport )
#endif


#ifdef BUILD_ARGUS_DISPLAY
#	define ARGUS_DISPLAY_API ARGUS_DISPLAY_EXPORT_DYNAMIC_LIBRARY
#else
#	define ARGUS_DISPLAY_API ARGUS_DISPLAY_IMPORT_DYNAMIC_LIBRARY
#endif

#endif //ARGUS_DISTRIBUTION_DISPLAY_HELPER_H
